export enum ConfigKeysEnum {
  NODE_ENVIRONMENT = 'NODE_ENV',
  SERVER_PORT = 'SERVER_PORT',
  SERVER_HOST = 'SERVER_HOST',
  DATABASE_PORT = 'DATABASE_PORT',
  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_USER = 'DATABASE_USER',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  DATABASE_NAME = 'DATABASE_NAME',
  JWT_SECRET_KEY = 'JWT_SECRET_KEY'
}
